// This file is auto-generated by @hey-api/openapi-ts
//
// Hand-maintained edits below - RE-APPLY AFTER REGENERATION:
//   1. The Service exports are routed through `./legacy-services` (facade) for
//      services we wrap; remaining ones come from `./sdk.gen`.
//   2. Compatibility shim exports (ApiError, OpenAPI, ...).
//   3. `Body_login_login_access_token` legacy snake_case alias.
//
// See `legacy-services.ts` for rationale.

// Pass-through services (no facade - generated SDK style is used directly)
export { AiApiService, AiMonitoringService, AiProxyService, AiPveLogService, BatchProvisionService, CloudflareService, DesktopClientService, FirewallService, GatewayService, GpuService, IpManagementService, JobsService, MigrationJobsService, type Options, ProxmoxConfigService, ReverseProxyService, RubricService, TunnelService, UtilsService } from './sdk.gen';

// Facaded services (legacy short method names + auto-unwrap)
export { AiTemplateRecommendationService, AuditLogsService, DeletionRequestsService, GroupsService, LoginService, LxcService, PrivateService, ResourceDetailsService, ResourcesService, ScriptDeployService, SpecChangeRequestsService, UsersService, VmRequestsService, VmService, VncConsoleService } from './legacy-services';

// Compatibility shims (hand-maintained - re-add these lines after regenerating the client)
export { ApiError } from './core/ApiError'
export type { CancelablePromise } from './core/CancelablePromise'
export { OpenAPI } from './core/OpenAPI'
export { client } from './client.gen'

// Legacy snake_case + uppercase type aliases for backward compatibility
export type { BodyLoginLoginAccessToken as Body_login_login_access_token, LxcCreateRequest as LXCCreateRequest, VmCreateRequest as VMCreateRequest, VmRequestCreate as VMRequestCreate, VmRequestPublic as VMRequestPublic, VmRequestStatus as VMRequestStatus, AppAiTemplateRecommendationSchemasChatRequest as ChatRequest, AppAiTemplateRecommendationSchemasChatResponse as ChatResponse } from './types.gen'

export type * from './types.gen'
