"""
Schemas 模組

API 請求/回應 schemas，按領域分檔（ai_api、firewall、gpu、monitoring、
resource、user、vm_request……每個領域一個子模組）。

本檔只把最常用的 schemas 重新匯出成 `from app.schemas import X`；
多數呼叫端直接從子模組匯入（例如 `from app.schemas.gpu import ...`），
新增的領域 schemas 不必一定加進這裡。
"""

from .ai_api import (
    AIAPICredentialAdminPublic,
    AIAPICredentialPublic,
    AIAPICredentialsAdminPublic,
    AIAPICredentialsPublic,
    AIAPICredentialUpdate,
    AIAPICredentialWithSecret,
    AIAPIRequestCreate,
    AIAPIRequestPublic,
    AIAPIRequestReview,
    AIAPIRequestsPublic,
)
from .ai_proxy import (
    RateLimitStatusResponse,
    UsageRecordPublic,
    UsageRecordsPublic,
    UsageStatsResponse,
)
from .audit_log import (
    AuditActionMeta,
    AuditLogPublic,
    AuditLogsPublic,
    AuditLogStats,
    AuditUserOption,
)
from .cloudflare import (
    CloudflareConfigPublic,
    CloudflareConfigUpdate,
    CloudflareConnectionTestResult,
    CloudflareDNSRecordCreate,
    CloudflareDNSRecordPublic,
    CloudflareDNSRecordsPublic,
    CloudflareDNSRecordUpdate,
    CloudflarePageInfoPublic,
    CloudflareZoneCreate,
    CloudflareZonePublic,
    CloudflareZonesPublic,
)
from .common import (
    Message,
    NewPassword,
    Token,
    TokenPayload,
    TotpChallenge,
    TotpLoginRequest,
)
from .deletion_request import (
    DeletionRequestCreated,
)
from .firewall import (
    ConnectionCreate,
    ConnectionDelete,
    FirewallOptionsPublic,
    FirewallRuleCreate,
    FirewallRulePublic,
    FirewallRuleUpdate,
    LayoutUpdate,
    PortSpec,
    TopologyEdge,
    TopologyNode,
    TopologyResponse,
)
from .ldap import (
    LdapConfigPublic,
    LdapConfigUpdate,
    LdapLoginRequest,
    LdapTestResult,
    LoginMethodsPublic,
)
from .mining import (
    MiningDismissRequest,
    MiningDismissResult,
    MiningIncidentPublic,
)
from .monitoring import (
    AlertEventPublic,
    GovernanceConfigPublic,
    GovernanceConfigUpdate,
    MonitoringIssue,
    MonitoringOverview,
    MonitoringSignal,
    MonitoringThresholds,
    NodeMetrics,
    VMTopEntry,
)
from .proxmox_config import (
    ProxmoxConfigPublic,
    ProxmoxConfigUpdate,
    ProxmoxConnectionTestResult,
)
from .quota import (
    EffectiveQuotaPublic,
    GlobalQuotaPublic,
    GlobalQuotaUpdate,
    QuotaUsagePublic,
    ResourceQuotaCreate,
    ResourceQuotaPublic,
    ResourceQuotaUpdate,
)
from .resource import (
    BackupCapability,
    BackupCreateRequest,
    BackupInfo,
    BackupRestoreRequest,
    BatchActionRequest,
    BatchActionResponse,
    BatchActionResultItem,
    CurrentStatsResponse,
    DirectSpecUpdateRequest,
    LXCCreateRequest,
    LXCCreateResponse,
    ResetAcceptedResponse,
    ResourcePublic,
    ResourceStatus,
    RRDDataPoint,
    RRDDataResponse,
    SnapshotCapability,
    SnapshotCreateRequest,
    SnapshotInfo,
    SnapshotResponse,
    SSHKeyResponse,
    TemplateSchema,
    TerminalInfoSchema,
    VMCreateRequest,
    VMCreateResponse,
    VMTemplateSchema,
    VNCInfoSchema,
)
from .spec_change_request import (
    SpecChangeApplyAccepted,
    SpecChangeRequestCreate,
    SpecChangeRequestPublic,
    SpecChangeRequestReview,
    SpecChangeRequestsPublic,
)
from .user import (
    TotpCodeRequest,
    TotpSetupPublic,
    TotpStatusPublic,
    UpdatePassword,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)
from .vm_request import (
    VMRequestAvailabilityDay,
    VMRequestAvailabilityNodeSnapshot,
    VMRequestAvailabilityRequest,
    VMRequestAvailabilityResponse,
    VMRequestAvailabilitySlot,
    VMRequestAvailabilityStackItem,
    VMRequestAvailabilitySummary,
    VMRequestCreate,
    VMRequestPublic,
    VMRequestReview,
    VMRequestReviewContext,
    VMRequestReviewNodeScore,
    VMRequestReviewOverlapItem,
    VMRequestReviewProjectedNode,
    VMRequestReviewRuntimeResource,
    VMRequestsPublic,
    VMRequestWindowAvailabilityRequest,
    VMRequestWindowAvailabilityResponse,
    WorkloadAdviceResponse,
    WorkloadAdviseRequest,
)

__all__ = [
    # Common
    "Message",
    "Token",
    "TokenPayload",
    "TotpChallenge",
    "TotpLoginRequest",
    "NewPassword",
    # Deletion Request
    "DeletionRequestCreated",
    # AI API
    "AIAPIRequestCreate",
    "AIAPIRequestReview",
    "AIAPIRequestPublic",
    "AIAPIRequestsPublic",
    "AIAPICredentialAdminPublic",
    "AIAPICredentialPublic",
    "AIAPICredentialsAdminPublic",
    "AIAPICredentialsPublic",
    "AIAPICredentialUpdate",
    "AIAPICredentialWithSecret",
    # AI Proxy
    "UsageStatsResponse",
    "UsageRecordPublic",
    "UsageRecordsPublic",
    "RateLimitStatusResponse",
    # User
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UpdatePassword",
    "UserPublic",
    "UsersPublic",
    "TotpCodeRequest",
    "TotpSetupPublic",
    "TotpStatusPublic",
    # Batch Operations
    "BatchActionRequest",
    "BatchActionResponse",
    "BatchActionResultItem",
    # Resource / Proxmox
    "VNCInfoSchema",
    "TerminalInfoSchema",
    "TemplateSchema",
    "VMTemplateSchema",
    "LXCCreateRequest",
    "LXCCreateResponse",
    "ResourcePublic",
    "ResourceStatus",
    "SSHKeyResponse",
    "VMCreateRequest",
    "VMCreateResponse",
    "CurrentStatsResponse",
    "RRDDataPoint",
    "RRDDataResponse",
    "SnapshotInfo",
    "SnapshotCapability",
    "SnapshotCreateRequest",
    "SnapshotResponse",
    "BackupCapability",
    "BackupCreateRequest",
    "BackupInfo",
    "BackupRestoreRequest",
    "DirectSpecUpdateRequest",
    "ResetAcceptedResponse",
    # VM Request
    "VMRequestAvailabilityRequest",
    "VMRequestAvailabilitySlot",
    "VMRequestAvailabilityStackItem",
    "VMRequestAvailabilityNodeSnapshot",
    "VMRequestAvailabilityDay",
    "VMRequestAvailabilitySummary",
    "VMRequestAvailabilityResponse",
    "VMRequestWindowAvailabilityRequest",
    "VMRequestWindowAvailabilityResponse",
    "VMRequestCreate",
    "VMRequestReview",
    "VMRequestPublic",
    "VMRequestReviewContext",
    "VMRequestReviewNodeScore",
    "VMRequestReviewOverlapItem",
    "VMRequestReviewProjectedNode",
    "VMRequestReviewRuntimeResource",
    "VMRequestsPublic",
    "WorkloadAdviceResponse",
    "WorkloadAdviseRequest",
    # Audit Log
    "AuditLogPublic",
    "AuditLogsPublic",
    "AuditLogStats",
    "AuditActionMeta",
    "AuditUserOption",
    # Cloudflare
    "CloudflareConfigPublic",
    "CloudflareConfigUpdate",
    "CloudflareConnectionTestResult",
    "CloudflarePageInfoPublic",
    "CloudflareZonePublic",
    "CloudflareZonesPublic",
    "CloudflareZoneCreate",
    "CloudflareDNSRecordPublic",
    "CloudflareDNSRecordsPublic",
    "CloudflareDNSRecordCreate",
    "CloudflareDNSRecordUpdate",
    # Spec Change Request
    "SpecChangeApplyAccepted",
    "SpecChangeRequestCreate",
    "SpecChangeRequestReview",
    "SpecChangeRequestPublic",
    "SpecChangeRequestsPublic",
    # Firewall
    "PortSpec",
    "ConnectionCreate",
    "ConnectionDelete",
    "FirewallRuleCreate",
    "FirewallRuleUpdate",
    "FirewallRulePublic",
    "FirewallOptionsPublic",
    "LayoutUpdate",
    "TopologyNode",
    "TopologyEdge",
    "TopologyResponse",
    # LDAP
    "LdapConfigPublic",
    "LdapConfigUpdate",
    "LdapLoginRequest",
    "LdapTestResult",
    "LoginMethodsPublic",
    # Monitoring / Governance
    "AlertEventPublic",
    "GovernanceConfigPublic",
    "GovernanceConfigUpdate",
    "MonitoringIssue",
    "MonitoringOverview",
    "MonitoringSignal",
    "MonitoringThresholds",
    "NodeMetrics",
    "VMTopEntry",
    # Mining (module D)
    "MiningDismissRequest",
    "MiningDismissResult",
    "MiningIncidentPublic",
    # Proxmox Config
    "ProxmoxConfigPublic",
    "ProxmoxConfigUpdate",
    "ProxmoxConnectionTestResult",
    # Quota (module E)
    "EffectiveQuotaPublic",
    "GlobalQuotaPublic",
    "GlobalQuotaUpdate",
    "QuotaUsagePublic",
    "ResourceQuotaCreate",
    "ResourceQuotaPublic",
    "ResourceQuotaUpdate",
]
