"""add batch_job_id to resource

Revision ID: 99116213834b
Revises: qt01_request_kind
Create Date: 2026-05-11 23:37:36.832251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '99116213834b'
down_revision = 'qt01_request_kind'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('batch_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'resources', 'batch_provision_jobs', ['batch_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'batch_job_id')
    # ### end Alembic commands ###
